workflows:
  gtmobile-app-android:
      scripts:
      # - name: Install NVM
      #   working_directory: /
      #   script: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      
      # - name: Export NVM for Global Use
      #   working_directory: /
      #   script: export NVM_DIR="$HOME/.nvm" 
      #           -s "NVM_DIR/nvm.sh"  && \. "NVM_DIR/nvm.sh" 
      #           -s "NVM_DIR/bash_completion" && \. "NVM_DIR/bash_completion" 

      # - name: Install Node
      #   working_directory: /
      #   script: nvm install 16.13.2 

      - name: List files
        script: ls 

      - name: Node version
        script: node -v 

      - name: NPM Version
        script: npm -v


      - name: NPM Install
        script: npm install react-native -g

      - name: React Native Assembly
        script: react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/

      - name: Remove Drawable
        script: rmdir -r android/app/src/main/res/drawable-*

      - name: Remove Raw
        script: rmdir -r android/app/src/main/res/raw/*

      - name: Give Gradle permission
        working_directory: android
        script: chmod 777 ./gradlew 

      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
      artifacts:
      - app/build/outputs/**/**/*.apk