workflows:
  gtmobile-app:
      scripts:
      - name: Build Android APK
        working_directory: android
        script: 
          chmod 777 ./gradlew
          ./gradlew assembleRelease
      artifacts:
      - app/build/outputs/**/**/*.apk