workflows:
  gtmobile-app-android:
      scripts:
      - name: Install NVM
        working_directory: /
        script: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

      - name: Install Node
        working_directory: /
        script: nvm install 16.13.2 

      - name: Install React-Native Globally
        working_directory: /
        script: npm install -g react-native-cli

      - name: React Native Assembly
        script: react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/

      - name: Remove Drawable
        script: rmdir -r android/app/src/main/res/drawable-*

      - name: Remove Raw
        script: rmdir -r android/app/src/main/res/raw/*

      - name: Give Gradle permission
        working_directory: android
        script: chmod 777 ./gradlew 

      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
      artifacts:
      - app/build/outputs/**/**/*.apk