workflows:
  gtmobile-app:
      scripts:
      - name: Build Android APK
        working_directory: android
        script: chmod +x ./gradlew assembleRelease
      artifacts:
      - app/build/outputs/**/**/*.apk