workflows:
  gtmobile-app:
      scripts:
      - name: Give Gradle permission
        working_directory: android
        script: chmod 777 ./gradlew 

      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
      artifacts:
      - app/build/outputs/**/**/*.apk